from collections.abc import Iterable
from io import UnsupportedOperation
from typing import override
from uuid import uuid4

from openqasm3.ast import Expression

from app.enricher import (
    Constraints,
    EnricherStrategy,
    EnrichmentResult,
    ImplementationMetaData,
)
from app.model.CompileRequest import (
    IfThenElseNode,
    ImplementationNode,
    PassNode,
)
from app.model.CompileRequest import Node as FrontendNode
from app.openqasm3.printer import leqo_dumps
from app.processing import ProcessorIfElse
from app.processing.graph import ProgramGraph, ProgramNode
from app.processing.merge import merge_if_nodes


class IfElseEnricherStrategy(EnricherStrategy):
    @override
    async def _enrich_impl(
        self,
        node: FrontendNode,
        constraints: Constraints | None,
    ) -> Iterable[EnrichmentResult]:
        if not isinstance(node, IfThenElseNode):
            return []

        if constraints is None:
            msg = "if-else-node requires constraints."
            raise UnsupportedOperation(msg)

        graphs: list[ProgramGraph] = []
        if_front_node = PassNode(id=f"autogenerated_pass_node_{uuid4().hex}")
        endif_front_node = PassNode(id=f"autogenerated_pass_node_{uuid4().hex}")
        if_node = ProgramNode(if_front_node.id)
        endif_node = ProgramNode(endif_front_node.id)
        for nested_block in (node.thenBlock, node.elseBlock):
            nested_block.nodes.extend([if_front_node, endif_front_node])
            for edge in nested_block.edges:
                if edge.source[0] == node.id:
                    edge.source = (if_front_node.id, edge.source[1])
                if edge.target[0] == node.id:
                    edge.target = (endif_front_node.id, edge.target[1])

            processor = ProcessorIfElse(
                nested_block.nodes,
                nested_block.edges,
                (if_node, if_front_node),
                (endif_node, endif_front_node),
                constraints.optimizeWidth,
                constraints.optimizeDepth,
            )
            graphs.append(await processor.process())

        then_graph, else_graph = tuple(graphs)
        processed_if_node = then_graph.node_data[if_node]
        processed_endif_node = then_graph.node_data[endif_node]

        implementation, out_size = merge_if_nodes(
            processed_if_node,
            processed_endif_node,
            then_graph,
            else_graph,
            Expression(),  # todo: parse expression
        )
        enriched_node = ImplementationNode(
            id=node.id,
            implementation=leqo_dumps(implementation),
        )
        metadata = ImplementationMetaData(width=out_size, depth=None)
        return [EnrichmentResult(enriched_node=enriched_node, meta_data=metadata)]
