services:
  leqo-backend:
    image: ghcr.io/leqo-framework/leqo-backend:main
    env_file: ".env"
    ports:
      - "8000:80"
  postgres:
    image: postgres:16-alpine3.20
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
