"""
Groovy script templates for BPMN service tasks.
"""

PAYLOAD_CREATE_DEPLOYMENT = """
import groovy.json.JsonBuilder

def circuit = execution.getVariable("circuit")

def program = [
    programs: [
        [
            quantumCircuit: circuit,
assemblerLanguage: "QASM3",
            pythonFilePath: "",
            pythonFileMetadata: ""
        ]
    ],
    name: "DeploymentName"
]

return new JsonBuilder(program).toPrettyString()
"""

OUTPUT_DEPLOYMENT_ID = """
import groovy.json.JsonSlurper

def resp = new JsonSlurper()
    .parseText(connector.getVariable("response"))

return resp.id
"""

PAYLOAD_EXECUTE_JOB = """
import groovy.json.JsonBuilder

def deploymentId = execution.getVariable("deploymentId")

def program = [
    name           : "JobName",
    providerName   : "IBM",
    deviceName     : "aer_simulator",
    shots          : 1024,
    errorMitigation: "none",
    cutToWidth     : null,
    token          : "",
    type           : "RUNNER",
    deploymentId   : deploymentId
]

def requestString = new JsonBuilder(program).toPrettyString()

return requestString
"""

OUTPUT_JOB_ID = """
import groovy.json.JsonSlurper

def resp = new JsonSlurper()
    .parseText(connector.getVariable("response"))

return resp.self
"""

OUTPUT_RESULT_EXECUTION = """
import groovy.json.JsonSlurper
import groovy.json.JsonBuilder

def resp = new JsonSlurper()
    .parseText(connector.getVariable("response"))

return new JsonBuilder(resp.results).toString()
"""

OUTPUT_STATUS_JOB = """
import groovy.json.JsonSlurper

def resp = new JsonSlurper()
    .parseText(connector.getVariable("response"))

return resp.state
"""

SCRIPT_SET_VARS_2 = """
def status = execution.getVariable("statusJob")
def containsPlaceholder = execution.getVariable("containsPlaceholder") == true

// defensive defaults
def jobFailed   = false
def shouldRetry = false
def isCompleted = false

if (containsPlaceholder) {

    // complex logic
    def iterations = execution.getVariable("iterations") ?: 0
    def MAX_RETRIES = 10

    if (status == "COMPLETED") {
        isCompleted = true
    }
    else if (status == "FAILED") {
        jobFailed = true
    }
    else {
        if (iterations < MAX_RETRIES) {
            shouldRetry = true
        } else {
            jobFailed = true
        }
    }

    execution.setVariable("iterations", iterations + 1)

} else {

    if (status == "FINISHED") {
        isCompleted = true
    }
    else if (status == "ERROR") {
        jobFailed = true
    }
    else {
        shouldRetry = true
    }
}

// evaluation variables
execution.setVariable("isCompleted", isCompleted)
execution.setVariable("shouldRetry", shouldRetry)
execution.setVariable("jobFailed", jobFailed)
"""

SCRIPT_SET_VARS_1 = """
            def model = '''
            {
            "metadata": {
                "version": "1.0.0",
                "name": "Auto Model",
                "description": "Generated by Camunda",
                "author": "Camunda",
                "containsPlaceholder": true
            },
            "nodes": [],
            "edges": []
            }
            '''

            // defensive initialization
            execution.setVariable("jobFailed", false)
            execution.setVariable("shouldRetry", false)
            execution.setVariable("isCompleted", false)

            execution.setVariable("model", model)

            def groupId = execution.getVariable("groupId")
            execution.setVariable("groupId", groupId == null ? 0 : groupId + 1)

            def iterations = execution.getVariable("iterations")
            execution.setVariable("iterations", execution.getVariable("iterations") ?: 0)
"""

PAYLOAD_BACKEND_REQ = """
import groovy.json.JsonSlurper
import groovy.json.JsonBuilder

def modelStr = execution.getVariable("model")
def modelObj = new JsonSlurper().parseText(modelStr)
return new JsonBuilder(modelObj).toPrettyString()
"""

OUTPUT_UUID = """
import groovy.json.JsonSlurper

def resp = new JsonSlurper()
    .parseText(connector.getVariable("response"))

return resp.uuid
"""

OUTPUT_STATUS = """
import groovy.json.JsonSlurper

def resp = new JsonSlurper()
    .parseText(connector.getVariable("response"))

return resp.status
"""

OUTPUT_CIRCUIT = """
return connector.getVariable("response")
"""

SCRIPT_UPDATE_VARS = """
def status = execution.getVariable("status")

def isCompleted = (status?.toLowerCase() == "completed")
execution.setVariable("isCompleted", isCompleted)

def iterations = execution.getVariable("iterations") ?: 0
def shouldRetry = (!isCompleted && iterations < 10)
execution.setVariable("shouldRetry", shouldRetry)

execution.setVariable("jobFailed", !isCompleted && !shouldRetry)
"""

SCRIPT_SET_CIRCUIT = """
// defensive initialization
execution.setVariable("jobFailed", false)
execution.setVariable("shouldRetry", false)
execution.setVariable("isCompleted", false)
execution.setVariable("iterations", execution.getVariable("iterations") ?: 0)

// --- QASM placeholder ---
// TODO: replace with real QASM string from modeler/backend
def qasmPlaceholder = '''
OPENQASM 3.1;
include "stdgates.inc";
qubit[1] q;
h q[0];
'''

execution.setVariable("circuit", qasmPlaceholder)

return true
"""