%%{init: {"flowchart": {"defaultRenderer": "elk", "curve": "linear"}, "theme": "neutral"} }%%
flowchart LR
    start((CompileRequest)) --> m2m
    subgraph graph[Operates on Graph]
        m2m(Model transformation) --> nodes
        subgraph nodes[For each node]
            direction TB

            enrich(Enricher) --> convert(Converter <br> v2 → v3)
            convert --> pre(Preprocessing)
        end
        nodes --> choice{optimizeWidth}
        choice -->|no| merge(Serialization)
        choice -- yes --> optimize(Optimization)
    end
    optimize --> merge
    merge --> post(Postprocessing)
    post --> final((Final Program))