name: Continuous Integration
on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync --all-extras --all-groups --locked

      - name: Type checking
        run: uv run --no-sync mypy . --strict

      - name: Run tests
        run: uv run --no-sync pytest tests

  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Lint
        uses: astral-sh/ruff-action@v3
        with:
          version-file: pyproject.toml
          args: check --no-fix

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check format
        uses: astral-sh/ruff-action@v3
        with:
          version-file: pyproject.toml
          args: format --diff
