name: Documentation

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.artifact }}

    permissions:
      pages: write
      id-token: write

    steps:
      - id: deployment
        uses: sphinx-notes/pages@v3
        with:
          publish: 'false'
